### ISSUE TITLE
Using cpu for testing?

### ISSUE THREAD

**Issue by watchernyu** [facebookresearch/RRL#1]
First of all thank you very much for presenting this nice paper and open source the code! 

I'm wondering if it's possible to use cpu instead of gpu to do some testing on my local machine (which unfortunately does not have a cuda gpu)? I tried to modify the code a bit and run (I have the demo files under ../demo)

`
python convertDemos.py --env_name hammer-v0 --encoder_type resnet34 -c top -d ../demo/hammer-v0_demos.pickle
`

Then it gives me the following error, 
`
ERROR: GLEW initalization error: Missing GL version
`
which occurs at the rendering line in multicam.py:
`img = self._env.env.sim.render(width=self.width, height=self.height, mode='offscreen', camera_name=cam)`

Is there an easy way to ask mujoco to do cpu rendering here (software rendering)? Thanks a lot for the help!

**Comment by ShahRutav** [comment]
Hi @watchernyu,

The error is related to installation of `mujoco_py`. Please check this [thread](https://github.com/openai/mujoco-py/issues/268), might be helpful. I believe, this error is due to some missing `mujoco_py` dependency. 

Regarding running the codebase on CPU, I will try to push an update soon, meanwhile these pointers might be helpful:  
   1) You can simply add an if-else statement [here](https://github.com/facebookresearch/RRL/blob/26e91d309588d930b6674c6f0da4c8b45bcfecb2/rrl/multicam.py#L57) which will load the image and model on cpu/gpu.
   2) Similarly, you can adjust the rendering device_id of image [here](https://github.com/facebookresearch/RRL/blob/26e91d309588d930b6674c6f0da4c8b45bcfecb2/rrl/multicam.py#L31).

**Comment by watchernyu** [comment]
Thanks a lot for your response, that is very helpful! I will close the issue now.
